name: Auto-PR

on:
  push:
    branches: [dev]

jobs:
  auto-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: dev
          title: "Auto PR: dev → main"
          body: "This PR was created automatically."
