deploy:
  if: github.ref == 'refs/heads/main' && success()
  needs: build-test
  runs-on: ubuntu-latest

  steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          USERNAME="${{ secrets.EC2_USER }}"
          APP_DIR="/home/$USERNAME/myapp"

          mkdir -p $APP_DIR
          sudo chown $USERNAME:$USERNAME $APP_DIR

          cd $APP_DIR

          if [ ! -d .git ]; then
            git clone https://github.com/${{ github.repository }} .
          else
            git pull origin main
          fi

          pip3 install -r requirements.txt --quiet

          sudo systemctl daemon-reload
          sudo systemctl restart my-python-app || sudo systemctl start my-python-app
